Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = 'bpf'
    config.vm.define vm_name = 'bpf'
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.network :private_network, ip: "192.168.56.10"
    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
    end
end
