domain = "kubernetes.cch.lab"
control_plane_endpoint = "master." + domain + ":6443"
pod_network_cidr = "10.244.0.0/16"
master_node_ip = "192.168.56.100"
version = "1.26.0-00"

Vagrant.configure("2") do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.ssh.insert_key = false
    config.vm.provision :shell, path: "kubeadm/bootstrap.sh", env: { "VERSION" => version }
    config.vm.define "master" do |master|
      master.vm.box = "bento/ubuntu-22.04"
      master.vm.hostname = "master.#{domain}"
      master.vm.network "private_network", ip: "#{master_node_ip}"
      master.vm.provision "shell", env: {"DOMAIN" => domain, "MASTER_NODE_IP" => master_node_ip} ,inline: <<-SHELL 
      echo "$MASTER_NODE_IP master.$DOMAIN master" >> /etc/hosts 
      SHELL
      (1..2).each do |nodeIndex|
        master.vm.provision "shell", env: {"DOMAIN" => domain, "NODE_INDEX" => nodeIndex}, inline: <<-SHELL 
        echo "192.168.56.10$NODE_INDEX worker-$NODE_INDEX.$DOMAIN worker-$NODE_INDEX" >> /etc/hosts 
        SHELL
      end
      master.vm.provision "shell", path:"kubeadm/init-master.sh", env: {"K8S_CONTROL_PLANE_ENDPOINT" => control_plane_endpoint, "K8S_POD_NETWORK_CIDR" => pod_network_cidr, "MASTER_NODE_IP" => master_node_ip}
    end
    (1..2).each do |nodeIndex|
      config.vm.define "worker-#{nodeIndex}" do |worker|
        worker.vm.synced_folder '.', '/vagrant', disabled: true
        worker.vm.box = "bento/ubuntu-22.04"
        worker.vm.hostname = "worker-#{nodeIndex}.#{domain}"
        worker.vm.network "private_network", ip: "192.168.56.10#{nodeIndex}"
        worker.vm.provision "shell", env: {"DOMAIN" => domain, "MASTER_NODE_IP" => master_node_ip} ,inline: <<-SHELL 
        echo "$MASTER_NODE_IP master.$DOMAIN master" >> /etc/hosts 
        SHELL
        (1..2).each do |hostIndex|
            worker.vm.provision "shell", env: {"DOMAIN" => domain, "NODE_INDEX" => hostIndex}, inline: <<-SHELL 
            echo "192.168.57.10$NODE_INDEX worker-$NODE_INDEX.$DOMAIN worker-$NODE_INDEX" >> /etc/hosts 
            SHELL
        end
        worker.vm.provision "shell", env: {"MASTER_NODE_IP" => master_node_ip}, inline: <<-SHELL
            set -e -x -u
            export DEBIAN_FRONTEND=noninteractive
            ping -c3 master > /dev/null
            sudo apt-get install -y sshpass
            sshpass -p "vagrant" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no master:/home/vagrant/init-worker.sh . 2>/dev/null
            sudo ./init-worker.sh
            SHELL
        worker.vm.provision "shell", env: { "NODE_INDEX" => nodeIndex}, inline: <<-SHELL 
            echo ">>> FIX KUBELET NODE IP"
            echo "Environment=\"KUBELET_EXTRA_ARGS=--node-ip=192.168.56.10$NODE_INDEX\"" | sudo tee -a /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
            sudo systemctl daemon-reload
            sudo systemctl restart kubelet
            SHELL
      end
    end
    config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 3]
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
#      vb.memory = "4096"
#      vb.cpus = "3"
      vb.customize ["modifyvm", :id, "--nic1", "nat"]
    end
  end
  
